### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by DenisRoss** [arnabgho/iSketchNFill#1]
Hello, i make all like in "Getting Started" section, but have this problem:

```
python3 main_gui_shadow_draw_color.py --name wgangp_sparse_label_channel_pix2pix_autocomplete_multiscale_nz_256_nc_1_nf_32_gp_0_multigpu --model sparse_wgangp_pix2pix  --checkpoints_dir checkpoints_sparse --gpu_ids 0 --nz 256 --sparseSize 4 --fineSize 128 --ngf 32 --ndf 32 --num_interpolate 8 --input_nc 1 --output_nc 1
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=34 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "main_gui_shadow_draw_color.py", line 27, in <module>
    opt = TestOptions().parse()
  File "/home/username/dev/iSketchNFill/options/base_options.py", line 103, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/home/username/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/torch/csrc/cuda/Module.cpp:34
```
I haven't gpu on this computer. How can i start iSketchNFill using cpu?

**Comment by arnabgho** [comment]
I think at the moment its only supported on GPU machines, you can refactor the code slightly to make it work on CPU I believe because the weights are provided. Although I am not sure whether the real time capabilities would still be intact.
